// Generated forwarders for official nvngx_dlssnr.dll surface
// ─────────────────────────────────────────────────────────────────────────────
// 转发原理：链接器 /export 把绝大多数 NGX 导出直接指向 nvngx_dlssnr_real.dll
// （原版 DLL 的改名）。注意 D3D12 系列导出【没有】 "=nvngx_dlssnr_real." 后缀
// ——那几个由 proxy_main.cpp 自己实现（我们要拦截它们做降采样/合成），
// 内部经 real_* 函数指针调用原版。real_* 指针在 forwarders.h 里声明、
// proxy_main.cpp 的 EnsureRealModuleLoaded() 里 LoadLibraryW 赋值。
// ⚠️ 崩溃防线：游戏持有的真实 feature 句柄一旦进入延迟回收（ParkNrFeature），
//    绝不能再经 real_Evaluate 转发——0.7.x 的 use-after-free 教训见文件头。
// ─────────────────────────────────────────────────────────────────────────────
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_CreateFeature=nvngx_dlssnr_real.NVSDK_NGX_CUDA_CreateFeature")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_CreateFeature1=nvngx_dlssnr_real.NVSDK_NGX_CUDA_CreateFeature1")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_EvaluateFeature=nvngx_dlssnr_real.NVSDK_NGX_CUDA_EvaluateFeature")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_GetFeatureRequirements=nvngx_dlssnr_real.NVSDK_NGX_CUDA_GetFeatureRequirements")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_GetScratchBufferSize=nvngx_dlssnr_real.NVSDK_NGX_CUDA_GetScratchBufferSize")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_Init=nvngx_dlssnr_real.NVSDK_NGX_CUDA_Init")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_Init1=nvngx_dlssnr_real.NVSDK_NGX_CUDA_Init1")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_Init_Ext=nvngx_dlssnr_real.NVSDK_NGX_CUDA_Init_Ext")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_Init_Ext1=nvngx_dlssnr_real.NVSDK_NGX_CUDA_Init_Ext1")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_PopulateParameters_Impl=nvngx_dlssnr_real.NVSDK_NGX_CUDA_PopulateParameters_Impl")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_ReleaseFeature=nvngx_dlssnr_real.NVSDK_NGX_CUDA_ReleaseFeature")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_Shutdown=nvngx_dlssnr_real.NVSDK_NGX_CUDA_Shutdown")
#pragma comment(linker, "/export:NVSDK_NGX_CUDA_Shutdown1=nvngx_dlssnr_real.NVSDK_NGX_CUDA_Shutdown1")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_CreateFeature=nvngx_dlssnr_real.NVSDK_NGX_D3D11_CreateFeature")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_EvaluateFeature=nvngx_dlssnr_real.NVSDK_NGX_D3D11_EvaluateFeature")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_GetFeatureRequirements=nvngx_dlssnr_real.NVSDK_NGX_D3D11_GetFeatureRequirements")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_GetScratchBufferSize=nvngx_dlssnr_real.NVSDK_NGX_D3D11_GetScratchBufferSize")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_Init=nvngx_dlssnr_real.NVSDK_NGX_D3D11_Init")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_Init_Ext=nvngx_dlssnr_real.NVSDK_NGX_D3D11_Init_Ext")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_PopulateParameters_Impl=nvngx_dlssnr_real.NVSDK_NGX_D3D11_PopulateParameters_Impl")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_ReleaseFeature=nvngx_dlssnr_real.NVSDK_NGX_D3D11_ReleaseFeature")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_Shutdown=nvngx_dlssnr_real.NVSDK_NGX_D3D11_Shutdown")
#pragma comment(linker, "/export:NVSDK_NGX_D3D11_Shutdown1=nvngx_dlssnr_real.NVSDK_NGX_D3D11_Shutdown1")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_CreateFeature")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_EvaluateFeature")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_GetFeatureRequirements=nvngx_dlssnr_real.NVSDK_NGX_D3D12_GetFeatureRequirements")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_GetScratchBufferSize=nvngx_dlssnr_real.NVSDK_NGX_D3D12_GetScratchBufferSize")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_Init=nvngx_dlssnr_real.NVSDK_NGX_D3D12_Init")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_Init_Ext")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_PopulateParameters_Impl=nvngx_dlssnr_real.NVSDK_NGX_D3D12_PopulateParameters_Impl")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_ReleaseFeature")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_Shutdown=nvngx_dlssnr_real.NVSDK_NGX_D3D12_Shutdown")
#pragma comment(linker, "/export:NVSDK_NGX_D3D12_Shutdown1=nvngx_dlssnr_real.NVSDK_NGX_D3D12_Shutdown1")
#pragma comment(linker, "/export:NVSDK_NGX_GetAPIVersion=nvngx_dlssnr_real.NVSDK_NGX_GetAPIVersion")
#pragma comment(linker, "/export:NVSDK_NGX_GetApplicationId=nvngx_dlssnr_real.NVSDK_NGX_GetApplicationId")
#pragma comment(linker, "/export:NVSDK_NGX_GetDriverVersionEx=nvngx_dlssnr_real.NVSDK_NGX_GetDriverVersionEx")
#pragma comment(linker, "/export:NVSDK_NGX_GetGPUArchitecture=nvngx_dlssnr_real.NVSDK_NGX_GetGPUArchitecture")
#pragma comment(linker, "/export:NVSDK_NGX_GetSnippetVersion=nvngx_dlssnr_real.NVSDK_NGX_GetSnippetVersion")
#pragma comment(linker, "/export:NVSDK_NGX_SetOverrideStatusCallback=nvngx_dlssnr_real.NVSDK_NGX_SetOverrideStatusCallback")
#pragma comment(linker, "/export:NVSDK_NGX_SetRuntimeParamsCallback=nvngx_dlssnr_real.NVSDK_NGX_SetRuntimeParamsCallback")
#pragma comment(linker, "/export:NVSDK_NGX_SetTelemetryEvaluateCallback=nvngx_dlssnr_real.NVSDK_NGX_SetTelemetryEvaluateCallback")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_CreateFeature=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_CreateFeature")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_CreateFeature1=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_CreateFeature1")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_EvaluateFeature=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_EvaluateFeature")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_GetFeatureRequirements=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_GetFeatureRequirements")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_GetScratchBufferSize=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_GetScratchBufferSize")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_Init=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_Init")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_Init_Ext=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_Init_Ext")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_Init_Ext2=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_Init_Ext2")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_PopulateParameters_Impl=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_PopulateParameters_Impl")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_ReleaseFeature=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_ReleaseFeature")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_Shutdown=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_Shutdown")
#pragma comment(linker, "/export:NVSDK_NGX_VULKAN_Shutdown1=nvngx_dlssnr_real.NVSDK_NGX_VULKAN_Shutdown1")